version: "3"

# 어떤 컨테이너를 돌릴지
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/my-app/app
    ports:
      - "4000:4000"
    env_file:
      - .env 
    environment:
      PORT: 4000
    depends_on:
      - redis
  redis: 
    image: "redis:alpine"
